---
# tasks file for perfsonar-psconfig-publisher

- name: Copy psconfig JSON meshes to publisher hosts
  tags: [ 'ps::config' ]
  copy:
    src: "{{ item }}"
    dest: "{{ perfsonar_psconfig_publish_dir }}"
  with_items: "{{ perfsonar_psconfig_publish_files | default([]) }}"

- name: Publish psconfig JSON meshes
  tags: [ 'ps::config' ]
  command: psconfig publish "{{ perfsonar_psconfig_publish_dir }}/{{ item }}"
  with_items: "{{ perfsonar_psconfig_publish_files | default([]) }}"
  register: "psconfig_urls"

- name: Alert psconfig agents on remote hosts
  tags: [ 'ps::config' ]
  command: >
    psconfig remote add "{{ item[0].stdout | regex_search( '\"(.*?)\"' ) }}"
  delegate_to: "{{ item[1] }}"
  loop: >
    {{ psconfig_urls.results |
    product(perfsonar_psconfig_publish_remote_agents) |
    list }}
